# services:
#   postgres:
#     image: postgres:15
#     container_name: souknova-postgres
#     environment:
#       POSTGRES_USER: soukadmin
#       POSTGRES_PASSWORD: password
#       POSTGRES_DB: souknovadb
#     volumes:
#       - pgdata:/var/lib/postgresql/data
#     ports:
#       - "5432:5432"

#   backend:
#     build: ./backend
#     container_name: souknova-backend
#     ports:
#       - "3001:3001"
#     env_file:
#       - ./backend/.env
#     depends_on:
#       - postgres
#     volumes:
#       - ./backend:/app
#       - backend_node_modules:/app/node_modules
#     networks:
#       - souknova-net


# networks:
#   souknova-net:
#     driver: bridge

# volumes:
#   backend_node_modules:
#   frontend_node_modules:
#   pgdata:

services:
  postgres:
    image: postgres:15
    container_name: souknova-postgres
    env_file:
      - ./backend/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: souknova-backend
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: souknova-frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules

volumes:
  backend_node_modules:
  frontend_node_modules:
  pgdata:
