services:
  postgres:
    image: postgres:15
    container_name: souknova-postgres
    env_file:
      - ./backend/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - souknova-net

  redis:
    image: redis:7-alpine
    container_name: souknova-redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    env_file:
      - ./backend/.env
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - souknova-net

  backend:
    build: ./backend
    container_name: souknova-backend
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
      - redis
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - souknova-net

  frontend:
    build: ./frontend
    container_name: souknova-frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    volumes:
      - frontend_node_modules:/app/node_modules
    networks:
      - souknova-net

networks:
  souknova-net:
    driver: bridge

volumes:
  backend_node_modules:
  frontend_node_modules:
  pgdata:
  redisdata:
